services:
  whisperx-api-1:
    image: taftiz/whisper-offline-image:latest
    pull_policy: never
    gpus: all
    expose:
      - "8000"
    volumes:
      - ./data/models:/app/data/models
    environment:
      - HF_HOME=/app/data/models
      - HF_HUB_OFFLINE=1
      - TRANSFORMERS_OFFLINE=1
      - HF_DATASETS_OFFLINE=1
      - TORCH_HOME=/app/data/models/torch
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - MAX_CONCURRENT_TRANSCRIPTIONS=2
    restart: unless-stopped

  whisperx-api-2:
    image: taftiz/whisper-offline-image:latest
    pull_policy: never
    gpus: all
    expose:
      - "8000"
    volumes:
      - ./data/models:/app/data/models
    environment:
      - HF_HOME=/app/data/models
      - HF_HUB_OFFLINE=1
      - TRANSFORMERS_OFFLINE=1
      - HF_DATASETS_OFFLINE=1
      - TORCH_HOME=/app/data/models/torch
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - MAX_CONCURRENT_TRANSCRIPTIONS=2
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    container_name: whisperx-nginx
    depends_on:
      - whisperx-api-1
      - whisperx-api-2
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
